### ISSUE TITLE
Pytest fails all tests

### ISSUE THREAD

**Issue by aviskase** [rlaboiss/pelican_md_graphviz#1]
Continuation of https://github.com/rlaboiss/pelican-linkclass/issues/3 

I've started working on preparing this plugin and [pelican_md_include](https://github.com/rlaboiss/pelican_md_include) for PyPI. Currently pytest fails tests for them. I've tried fixing obvious problems like import or missing date, but ended up with failing assertions.

**Comment by rlaboiss** [comment]
Excuse me for the very belated reply. I have recently [filed](https://github.com/getpelican/pelican-plugins/issues/1311#issue-756177051) for migrating this plugin, as well as [pelican_md_include](https://github.com/rlaboiss/pelican_md_include), to the new 
Pelican Plugins organization.  Any efforts regarding the move into PyPI should be done in the contexte of this migration.

**Comment by aviskase** [comment]
Cool, good luck!
(personally, I already migrated to Hugo)
